name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
        name: Get tag name
        uses: olegtarasov/get-tag@v2
    -
       name: Build
       run: |
          cd selenoid && docker build -f Dockerfile -t getcarrier/observer-firefox:$GIT_TAG_NAME . --build-arg VERSION=$GIT_TAG_NAME
    -
       name: Push
       run: |
         docker push getcarrier/observer-firefox:$GIT_TAG_NAME
